/*
Carlos Silva
Rafael Alan
Jose Henrique
Gabriel Primo
Pedro Pataro
Wanderley Silva
*/
package Client_side;

import java.awt.Color;
import java.io.PrintStream;
import java.net.Socket;
import java.util.ArrayList;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    PrintStream saida;
    public String nome;
    String id;
    int n;
    int e;
    public RSA rsa; 
    public Recebedor recebedor;
    
    public NewJFrame(PrintStream saida,RSA rsa, Recebedor recebedor) {
        this.saida = saida;
        this.rsa = rsa;
        this.recebedor = recebedor;
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_imp1 = new javax.swing.JButton();
        bt_imp2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_imp3 = new javax.swing.JButton();
        cp_nome = new javax.swing.JTextField();
        label_nome = new javax.swing.JLabel();
        label_nome1 = new javax.swing.JLabel();
        cp_id = new javax.swing.JTextField();
        bt_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_imp1.setBackground(new java.awt.Color(153, 153, 153));
        bt_imp1.setForeground(new java.awt.Color(255, 255, 255));
        bt_imp1.setText("impressora1");
        bt_imp1.setEnabled(false);
        bt_imp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_imp1MouseClicked(evt);
            }
        });

        bt_imp2.setBackground(new java.awt.Color(153, 153, 153));
        bt_imp2.setForeground(new java.awt.Color(255, 255, 255));
        bt_imp2.setText("impressora2");
        bt_imp2.setEnabled(false);
        bt_imp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_imp2MouseClicked(evt);
            }
        });
        bt_imp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imp2ActionPerformed(evt);
            }
        });

        jLabel4.setText("         POOL DE IMPRESSORAS");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMaximumSize(new java.awt.Dimension(400, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(400, 14));

        bt_imp3.setBackground(new java.awt.Color(153, 153, 153));
        bt_imp3.setForeground(new java.awt.Color(255, 255, 255));
        bt_imp3.setText("impressora3");
        bt_imp3.setEnabled(false);
        bt_imp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_imp3MouseClicked(evt);
            }
        });
        bt_imp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imp3ActionPerformed(evt);
            }
        });

        cp_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_nomeActionPerformed(evt);
            }
        });

        label_nome.setText("Nome");

        label_nome1.setText("ID");

        bt_ok.setText("OK");
        bt_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(label_nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cp_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_imp1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(bt_imp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_imp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cp_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_imp1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_imp2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_imp3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_imp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_imp2ActionPerformed

    private void bt_imp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_imp3ActionPerformed

    private void bt_imp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_imp1MouseClicked
        String vet = "U0";
        System.out.println("Solicitando recurso 1");
        System.out.println("msg Original: " + vet);
        ArrayList<Integer> lista;
        lista = rsa.chy(vet, this.recebedor._e, this.recebedor._n);
        System.out.println("msg cifrada: " + lista.toString());
        System.out.println("=======================================\n");
        this.saida.println(lista.toString());
    }//GEN-LAST:event_bt_imp1MouseClicked

    private void cp_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_nomeActionPerformed

    private void bt_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_okMouseClicked
        String vet = "L" + this.cp_nome.getText() + this.cp_id.getText();
        System.out.println("enviando requesicao de login:");
        System.out.println("msg Original: " + vet);
        ArrayList<Integer> lista;
        lista = rsa.chy(vet, this.recebedor._e, this.recebedor._n);
        System.out.println("msg cifrada: " + lista.toString());
        System.out.println("=======================================\n");
        this.saida.println(lista.toString());
    }//GEN-LAST:event_bt_okMouseClicked

    private void bt_imp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_imp2MouseClicked
        String vet = "U1";
        System.out.println("Solicitando recurso 2");
        System.out.println("msg Original: " + vet);
        ArrayList<Integer> lista;
        lista = rsa.chy(vet, this.recebedor._e, this.recebedor._n);
        System.out.println("msg cifrada: " + lista.toString());
        System.out.println("=======================================\n");
        this.saida.println(lista.toString());
    }//GEN-LAST:event_bt_imp2MouseClicked

    private void bt_imp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_imp3MouseClicked
        String vet = "U2";
        System.out.println("Solicitando recurso 3");
        System.out.println("msg Original: " + vet);
        ArrayList<Integer> lista;
        lista = rsa.chy(vet, this.recebedor._e, this.recebedor._n);
        System.out.println("msg cifrada: " + lista.toString());
        System.out.println("=======================================\n");
        this.saida.println(lista.toString());
    }//GEN-LAST:event_bt_imp3MouseClicked
    public void setCor(String status){
        String a = status.substring(0, 1);
        String b = status.substring(1, 2);
        String c = status.substring(2, 3);
        if(a.equals("0"))this.bt_imp1.setBackground(Color.green);
        if(a.equals("1"))this.bt_imp1.setBackground(Color.red);
        if(b.equals("0"))this.bt_imp2.setBackground(Color.green);
        if(b.equals("1"))this.bt_imp2.setBackground(Color.red);
        if(c.equals("0"))this.bt_imp3.setBackground(Color.green);
        if(c.equals("1"))this.bt_imp3.setBackground(Color.red);
    }
    public void enab(){
        this.cp_nome.setEnabled(false);
        this.cp_id.setEnabled(false);
        this.bt_imp1.setEnabled(true);
        this.bt_imp2.setEnabled(true);
        this.bt_imp3.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_imp1;
    private javax.swing.JButton bt_imp2;
    private javax.swing.JButton bt_imp3;
    private javax.swing.JButton bt_ok;
    private javax.swing.JTextField cp_id;
    private javax.swing.JTextField cp_nome;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_nome1;
    // End of variables declaration//GEN-END:variables
}
